# Generated by Django 3.1.6 on 2021-03-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=64)),
                ('preco', models.FloatField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=64)),
                ('endereco', models.CharField(max_length=256)),
                ('telefone', models.IntegerField(max_length=9)),
            ],
        ),
    ]
