# Generated by Django 3.1.6 on 2021-03-20 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210320_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='preco',
        ),
        migrations.CreateModel(
            name='Loja_Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preco', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.loja')),
            ],
        ),
    ]
